// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR7yAnXvpqoPXUxpzonHD56_7L2g-c0A4',
    appId: '1:124776215418:web:5bcd57be30cc4605d89cc3',
    messagingSenderId: '124776215418',
    projectId: 'expense-tracker-3c082',
    authDomain: 'expense-tracker-3c082.firebaseapp.com',
    storageBucket: 'expense-tracker-3c082.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb9xPlfZHEdcfQqBJ2dNhPrRYYUIhJKxM',
    appId: '1:124776215418:android:03006201e23263fad89cc3',
    messagingSenderId: '124776215418',
    projectId: 'expense-tracker-3c082',
    storageBucket: 'expense-tracker-3c082.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDkMqSNFUc3LdIp8GnOt8DuRzEvWsF8OY',
    appId: '1:124776215418:ios:9b59f11ff91d61d8d89cc3',
    messagingSenderId: '124776215418',
    projectId: 'expense-tracker-3c082',
    storageBucket: 'expense-tracker-3c082.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );
}
